### ISSUE TITLE
Feature Request: Better error message for dual_carriage

### ISSUE THREAD

**Issue by lukeslaboratory** [DangerKlippers/danger-klipper#115]
Currently there isn't a "smart" error when using dual_carriage in corexy mode - it responds with the below: 
![image](https://github.com/DangerKlippers/danger-klipper/assets/47956552/0020b39b-9aab-41ea-bcb2-84c14730ef91)

Ideally, this would provide a more useful error message like "dual_carriage not compatible with currently selected kinematics system" prompting the user (like dum-dum me) to make sure they're trying to use it correctly.

**Comment by lraithel15133** [comment]
Please test this when you have the time @lukeslaboratory #146

**Comment by lraithel15133** [comment]
#146 merged a fix/enhancement
