### ISSUE TITLE
Feature Request: Additional Parameter - inital_horizontal_move_z for gantry leveling

### ISSUE THREAD

**Issue by AlbinoDeer** [DangerKlippers/danger-klipper#123]
Perhaps an idea that should be simple to implement, but it would would be nice to have another parameter in the Z Tilt / QGL section of the config to adjust the gantry height lower to the bed after the initial correction. Essentially, after the initial lap of the gantry level, the second lap (and however many retries it does) can be much closer to the bed. This would allow the horizontal_move_z parameter to be very close to the bed, while initial_horizontal_move_Z could be much higher off the bed to avoid a gantry crash. This would cut down on gantry level times significantly if the probe lowering speed is relatively slow.

**Comment by kmobs** [comment]
This can already be done by overriding horizontal move Z in a macro for your ztilt/qgl. It was committed in mainline klipper by the beacon folks to help with scan mode, but can be used with all probes
