### ISSUE TITLE
Feature Request: Add Parameter to Load Mesh on Boot

### ISSUE THREAD

**Issue by lraithel15133** [DangerKlippers/danger-klipper#139]
I'd like to rework this commit [here](https://github.com/Klipper3d/klipper/commit/4df1adeb2e168b9b87856e738d3109a57ba1cac6) to instead load a mesh defined in the [bed_mesh] section. 
Behavior desired:
define in bed_mesh config block:
bed_mesh_default = [mesh name here]

If no default mesh defined, load nothing. If the specified mesh doesn't exist, either load nothing or give error.
Otherwise, load specified mesh on boot.

Idea from Mr. Leddhedd.

**Comment by rogerlz** [comment]
https://github.com/DangerKlippers/danger-klipper/pull/143
