### ISSUE TITLE
stm32h7.c hardcodes PLL_BASE to 5 MHz causing timing errors

### ISSUE THREAD

**Issue by calithameridi** [DangerKlippers/danger-klipper#147]
Clock configuration on stm32h7 hardcodes a PLL_BASE of 5 MHz due to an implicit assumption that HSE is a 25 MHz crystal oscillator, which works for BTT Octopus Pro and Kraken boards. Unfortunately this breaks timing on boards without 25 MHz (e.g. Corevus-G v0.4 with a 12 MHz on HSE) — for example, all moves execute at 20% greater velocity, and more critically a clock frequency above 2^(32) / (10 s) = 429 MHz causes integer overflow errors. 

![image](https://github.com/DangerKlippers/danger-klipper/assets/107025477/350c8494-c66b-4faa-95db-aa90c152d4c9)

**Comment by calithameridi** [comment]
I find that bodging the value of pll_base to 4 MHz allows me to successfully build an image with 400 MHz clock. Obviously this is not a permanent fix although it may suffice in providing pre-built firmware images to Corevus beta-testers

![image](https://github.com/DangerKlippers/danger-klipper/assets/107025477/febc59f5-2a3a-402d-9f6d-75dbad67b1c6)
![image](https://github.com/DangerKlippers/danger-klipper/assets/107025477/ebebe650-3d9a-461e-9d2e-a9823856d1e5)

**Comment by Fisheiyy** [comment]
This would also be good to PR into mainline klipper and fix it for EVERYONE, not just DK

**Comment by calithameridi** [comment]
> This would also be good to PR into mainline klipper and fix it for EVERYONE, not just DK

yeah but they don't have a convenient way of reporting issues
