### ISSUE TITLE
Feature Request: Tell me what sensor Klipper got its knickers in a bunch about

### ISSUE THREAD

**Issue by lukeslaboratory** [DangerKlippers/danger-klipper#161]
Has this ever happened to you?

"MCU 'mcu' shutdown: ADC out of range"

Well WHAT ADC???? You ask

Klipper says "ADC OUT OF RANGE"

So you go to the logs - sometimes, you can actually see the ADC that had the issue

Sometimes, its not captured, so you are just sitting there going "well wtf am i supposed to do now?"

Enter this feature request: 

Please have klipper tell us what ADC it freaked out about so I can troubleshoot better without having to dig into the logs and the exact error.

As a bonus, have it tell us what the actual temperature it saw and what it thinks the limit is

Thank you.

**Comment by theotherjimmy** [comment]
This will require an mcu firmware update, as the "ADC out of range" message is generated by that part of the firmware: https://github.com/DangerKlippers/danger-klipper/blob/288107c07e5b1f452474b5caac3bf072c32c1b9c/src/adccmds.c#L52
