### ISSUE TITLE
Lack of information and where to find it? 

### ISSUE THREAD

**Issue by TheVoronModder** [DangerKlippers/danger-klipper#215]
I am having a hard time figuring out how to get extra IS features working.

There are no clear instructions on how to accomplish these features.

Any help would be greatly appreciated!

**Comment by TheVoronModder** [comment]
Bleeding Edge installed on my system, using Klippain by frix_x

**Comment by bwnance** [comment]
From the readme - https://github.com/DangerKlippers/danger-klipper/blob/master/docs/Config_Reference_Bleeding_Edge.md
