### ISSUE TITLE
Feature Request: Add accel_per_hz to csv and png generation

### ISSUE THREAD

**Issue by lraithel15133** [DangerKlippers/danger-klipper#221]
I tried to do this but I'm too smooth. Basically, I want to pass accel_per_hz into the csv, and then also use it when the graph png is generated. The reason it needs to be passed into the csv is because the current value may not match the value from when the csv was created. 

- Pass it into the generated csv
- Add it somewhere that makes sense on the graph generation (above/below recommended shaper or something)

This should probably also be ported over to bleeding edge.

**Comment by lhndo** [comment]
On a similar note, I have this patch that adds the accel per hz parameter (APHZ) to the TEST_RESONANCES command.
I'm too github illiterate to do a PR myself and my coding skills are questionable 😅

https://github.com/lhndo/ResHelper/commit/13cdf5a4a75aab101b79e48178956a58cc65c1a6

**Comment by rogerlz** [comment]
Derp's request has been merged https://github.com/DangerKlippers/danger-klipper/pull/224
and LH's suggestion added to the backlog https://github.com/DangerKlippers/danger-klipper/issues/295
