### ISSUE TITLE
Please add description of "pin" in dockable_probe guide.

### ISSUE THREAD

**Issue by BelgarionNL** [DangerKlippers/danger-klipper#241]
https://dangerklipper.io/Dockable_Probe.html

not sure what "Pin" I need to add? z endstop pin?

**Comment by rogerlz** [comment]
_.. many of the options for the [probe] config section are the same. The [dockable_probe] module is first and foremost a [probe] but with additional functionality. Any options that can be specified for [probe] are valid for [dockable_probe]_
