### ISSUE TITLE
Make macros reloadable without having to restart Klipper

### ISSUE THREAD

**Issue by rschaeuble** [DangerKlippers/danger-klipper#286]
When developing complex macros, Klipper often has to be restarted for testing. This adds up to a lot of time. Especially when one needs to do things like homing every time before the macro can be tested.

To make macro development easier, it would be nice to have an ability to reload macros, e.g. by executing a command like `RELOAD_MACROS`.

TBD: should this reset gcode variables or not.

Resetting would give a clean slate for my own macros, and also handle the case of newly defined variables. But it would also reset the state of other macros (which I'm not working on), so it would modify the state of the printer.
I'm not sure which is the lesser evil.
Maybe being able to reload just the macros from one specific cfg file (including resetting variables) would solve this. Usually, when I work on macros, everything I'm working on is in the same file, so just reloading that would be fine.

**Comment by rogerlz** [comment]
Hey, this has been implemented now with https://github.com/DangerKlippers/danger-klipper/pull/305

You can run RELOAD_GCODE_MACROS to reload all existing macros. It won't add new ones or remove deleted ones.
We preferred not to reset the variables at this moment.. Maybe we can revisit that in the future. '

Ty for the suggestion.
