### ISSUE TITLE
heater_fan shutdown speed

### ISSUE THREAD

**Issue by Gethe** [DangerKlippers/danger-klipper#290]
On mainline Klipper I'm able to set `max_power: 0.95` on a `[heater_fan]`, to reduce noise without much effect on heater performance. In Danger Kilpper however, I'm getting this error:

```
shutdown value must be 0.0 or 1.0 on soft pwm
```

This seems to be related to the fan speed normalization feature (#44), since I get that error even if I explicitly set `shutdown_speed: 1.0`. It's only with `max_power: 1.0` that it doesn't error.

Not sure if this is intended or just an oversight, but IMO it doesn't make much sense to scale shutdown speed given it's purpose.

[klippy.log](https://github.com/user-attachments/files/15753293/klippy.log)

**Comment by rogerlz** [comment]
this is fixed now.. thanks!

**Comment by Gethe** [comment]
Thank you!
