### ISSUE TITLE
Add accels_per_hz as a parameter to `TEST_RESONANCES`

### ISSUE THREAD

**Issue by rogerlz** [DangerKlippers/danger-klipper#295]
Adding this to the backlog as suggested by @lhndo [here](https://github.com/DangerKlippers/danger-klipper/issues/221#issuecomment-2112295812)

https://github.com/lhndo/ResHelper/commit/13cdf5a4a75aab101b79e48178956a58cc65c1a6

**Comment by lhndo** [comment]
Great to see this @rogerlz !
I have CL with a more standard **ACCEL_PER_HZ** parameter along with updated documentation for the addition. 

https://github.com/lhndo/danger-klipper/commit/1c3d69b3b8c2ac9d2b392fc663ef3884c8da6a75
