### ISSUE TITLE
smart_effector.py references missing attribute in probe.py

### ISSUE THREAD

**Issue by timeburn** [DangerKlippers/danger-klipper#363]
The latest commit [82b779a] of smart_effector.py references functions in main Klipper's probe.py that have not been merged upstream:

  File "/home/timeburn/klipper/klippy/extras/smart_effector.py", line 186, in load_config
    smart_effector = SmartEffectorEndstopWrapper(config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/timeburn/klipper/klippy/extras/smart_effector.py", line 74, in __init__
    self.cmd_helper = probe.ProbeCommandHelper(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'extras.probe' has no attribute 'ProbeCommandHelper'

Reverting to commit 5ed6d70 allows it to load normally.

The function was introduced to probe.py here:
https://github.com/Klipper3d/klipper/commit/8fc11b4a2e0dd33cd99e4d3c8ce4107acf4772ff

**Comment by rogerlz** [comment]
Thanks. I am reverting this commit.
