### ISSUE TITLE
BTT Eddy Sensor Type not recognized "Option 'sensor_type' is not valid in section 'temperature_probe btt_eddy'"

### ISSUE THREAD

**Issue by mf7120** [DangerKlippers/danger-klipper#399]
As the title states, looks like the BTT Eddy (I am using the USB version) is not implemented. Attached Klippy logs and SS.

It does work in the standard Klipper installation.

[klippy.log](https://github.com/user-attachments/files/17549027/klippy.log)

![image](https://github.com/user-attachments/assets/e55e7831-8fa1-4b10-948d-4a9bbe4f00fa)

**Comment by rogerlz** [comment]
Hi, 

You are right, DK doesn't support the BTT Eddy sensors. We do not have plans to support them at the moment.

**Comment by mf7120** [comment]
Oh that's sad to hear. Thanks anyway
