### ISSUE TITLE
Bug with canbus Query

### ISSUE THREAD

**Issue by TessaKavanagh** [DangerKlippers/danger-klipper#445]
Hi, i flashed an STM32G0B1 (StealthMax2 PCB) with Katapult first, after that i flashed Klipper firmware. After flashing the "~/klippy-env/bin/python ~/klipper/scripts/canbus_query.py can0" was reporting Application CanBoot.

I could not get it report "Klipper" even after several trys. Even after flashing Klipper (without Katapult) the reporting showed CanBoot.

After a lot of help and trying katapults "python3 flashtool.py -i can0 -q" i realised that this one is reporting "klipper" where "~/klippy-env/bin/python ~/klipper/scripts/canbus_query.py can0" is showing CanBoot

DangerKlipper v0.12.0-520-g7aa9f3c0
![bug](https://github.com/user-attachments/assets/7b739118-d6fa-40c9-ad26-258e6abb9082)

**Comment by Drachenkaetzchen** [comment]
I was helping Tessa with figuring this out, it seems that there is a bug converting the application ID to the proper name. 

The board is in fact running in Klipper Mode, this is purely a display error.

**Comment by kageurufu** [comment]
The raw message received is `20bc9c1a451c5c11`

`0x20` is "RESP_NEEDS_NODEID" (e.g., Unassigned)
`0x11` is CanBoot/Katapults APP_ID

I'm sending `0x11` instead of `0x07` 🙃
