### ISSUE TITLE
Good Sensorless Minimum Homing Distance Comparison

### ISSUE THREAD

**Issue by lraithel15133** [DangerKlippers/danger-klipper#78]
I'm suggesting adding functionality to #65 that, on second home (via minimum homing distance), it compares the distance to the home move.
If homing retract distance is 10mm, you should see ~10mm worth of movement + some margin of error between the move start and it hitting the endstop. If you don't, throw an error as a sensorless homing fault has occurred.

Say your sensorless triggers mid X travel, it will retract 10mm and rehome. If it moves more than 10mm, it will throw a fault.
If your toolhead is at the endstop, and it hits the endstop, it will retract 10mm, rehome, calculate distance moved to be ~10mm, and will not throw a fault.

One issue with this idea is that it will not function if the distance traveled is OVER minimum homing distance/retract distance, but it triggers mid beam. 

Hopefully all of this makes sense.

**Comment by rogerlz** [comment]
can you check if https://github.com/DangerKlippers/danger-klipper/pull/90 satisfies what you need? It includes a `min_home_dist` parameter.
