### ISSUE TITLE
PULL over Klipper mainbranch declined feature: Firmware_retraction: Standard nozzle lifting on G10

### ISSUE THREAD

**Issue by YanceyA** [DangerKlippers/danger-klipper#81]
Flopana77 has done some good work on firmware retractions for Klipper. This PR was declined for resource reasons on the Klipper mainbranch. Could this feature be pulled over into DK or at least DK Bleeding Edge?

https://github.com/Klipper3d/klipper/pull/6311

Per the authors related work an extension of this feature is to add additional support for other types of z-hop moves.

**Comment by rogerlz** [comment]
https://github.com/DangerKlippers/danger-klipper/pull/83
